### ISSUE TITLE
Updatebot Task cannot connect to MySQL instance

### ISSUE THREAD

**Issue by tomrittervg** [mozilla-services/updatebot#168]
Seems to be an infrequent occurrence (this is the first I've seen) but putting it on file so we can track how many times it happens.

For an unknown reason, Updatebot can't connect to the sql proxy.

```
[task 2021-03-29T18:03:14.594Z] no sqlproxy output in 2 seconds, this means it probably didn't error.
[task 2021-03-29T18:03:14.594Z] Getting Updatebot ready...
[task 2021-03-29T18:03:14.594Z] Writing local config file
[task 2021-03-29T18:03:14.594Z] Running updatebot
[task 2021-03-29T18:03:15.417Z] Traceback (most recent call last):
[task 2021-03-29T18:03:15.417Z]   File "/builds/worker/.cache/pypoetry/virtualenvs/updatebot-VFmGBxYp-py3.7/lib/python3.7/site-packages/pymysql/connections.py", line 583, in connect
[task 2021-03-29T18:03:15.417Z]     **kwargs)
[task 2021-03-29T18:03:15.417Z]   File "/usr/lib/python3.7/socket.py", line 727, in create_connection
[task 2021-03-29T18:03:15.417Z]     raise err
[task 2021-03-29T18:03:15.417Z]   File "/usr/lib/python3.7/socket.py", line 716, in create_connection
[task 2021-03-29T18:03:15.417Z]     sock.connect(sa)
[task 2021-03-29T18:03:15.417Z] ConnectionRefusedError: [Errno 111] Connection refused
```

First occurrence: https://firefox-ci-tc.services.mozilla.com/tasks/Y65-olGBQcS80Buc-0euCg/runs/0

**Comment by tomrittervg** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1701747 got auto-filed for this too.

**Comment by tomrittervg** [comment]
And ~ 3 years later we got it again https://bugzilla.mozilla.org/show_bug.cgi?id=1928885
