### ISSUE TITLE
If pdfjs update fails, it doesn't do anything (file a bug/etc)

### ISSUE THREAD

**Issue by tomrittervg** [mozilla-services/updatebot#273]
```
[task 2022-08-10T12:06:06.534Z] [Info]    CommandProvider: Running ['./mach', 'vendor', 'toolkit/components/pdfjs/moz.yaml', '--revision', 'e1e97c6edd8729e968bde47f60a1901e8e649901']
[task 2022-08-10T12:06:23.511Z] [Info]    CommandProvider: Return: 254 Runtime (s): 16
[task 2022-08-10T12:06:23.511Z] [Debug]   CommandProvider: -------
[task 2022-08-10T12:06:23.511Z] [Debug]   CommandProvider: stdout:
[task 2022-08-10T12:06:23.511Z] [Debug]   CommandProvider: Latest commit is e1e97c6edd8729e968bde47f60a1901e8e649901 from 2022-08-10T09:13:00Z
[task 2022-08-10T12:06:23.511Z] Skipping fetching upstream source.
[task 2022-08-10T12:06:23.511Z] Updating files
[task 2022-08-10T12:06:23.511Z] action: run-script command: /builds/worker/checkouts/gecko/toolkit/components/pdfjs/update.sh working dir: /builds/worker/checkouts/gecko/toolkit/components/pdfjs args: ['e1e97c6edd8729e968bde47f60a1901e8e649901']
[task 2022-08-10T12:06:23.511Z] /builds/worker/checkouts/gecko/toolkit/components/pdfjs/update.sh e1e97c6edd8729e968bde47f60a1901e8e649901
[task 2022-08-10T12:06:23.511Z] ~/pdf.js ~/checkouts/gecko/toolkit/components/pdfjs
[task 2022-08-10T12:06:23.511Z] From https://github.com/mozilla/pdf.js
[task 2022-08-10T12:06:23.511Z]    e88c90e89..e1e97c6ed  master     -> origin/master
[task 2022-08-10T12:06:23.511Z]  + ba1347a2e...4f567b0b5 gh-pages   -> origin/gh-pages  (forced update)
[task 2022-08-10T12:06:23.511Z] Note: checking out 'e1e97c6edd8729e968bde47f60a1901e8e649901'.
[task 2022-08-10T12:06:23.511Z] 
[task 2022-08-10T12:06:23.511Z] You are in 'detached HEAD' state. You can look around, make experimental
[task 2022-08-10T12:06:23.511Z] changes and commit them, and you can discard any commits you make in this
[task 2022-08-10T12:06:23.511Z] state without impacting any branches by performing another checkout.
[task 2022-08-10T12:06:23.511Z] 
[task 2022-08-10T12:06:23.511Z] If you want to create a new branch to retain commits you create, you may
[task 2022-08-10T12:06:23.511Z] do so (now or later) by using -b with the checkout command again. Example:
[task 2022-08-10T12:06:23.511Z] 
[task 2022-08-10T12:06:23.511Z]   git checkout -b <new-branch-name>
[task 2022-08-10T12:06:23.511Z] 
[task 2022-08-10T12:06:23.511Z] HEAD is now at e1e97c6ed Merge pull request #15279 from Snuffleupagus/firefox-rm-README
[task 2022-08-10T12:06:23.511Z] npm WARN npm npm does not support Node.js v10.24.0
[task 2022-08-10T12:06:23.511Z] npm WARN npm You should probably upgrade to a newer version of node as we
[task 2022-08-10T12:06:23.511Z] npm WARN npm can't make any promises that npm will work with this version.
[task 2022-08-10T12:06:23.511Z] npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
[task 2022-08-10T12:06:23.511Z] npm WARN npm You can find the latest version at https://nodejs.org/
[task 2022-08-10T12:06:23.511Z] npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
[task 2022-08-10T12:06:23.511Z] npm WARN eslint-plugin-mozilla@2.12.4 requires a peer of eslint-plugin-html@^6.0.0 but none is installed. You must install peer dependencies yourself.
[task 2022-08-10T12:06:23.511Z] npm WARN eslint-plugin-mozilla@2.12.4 requires a peer of eslint-plugin-prettier@^3.0.0 but none is installed. You must install peer dependencies yourself.
[task 2022-08-10T12:06:23.511Z] npm WARN eslint-plugin-mozilla@2.12.4 requires a peer of prettier@^1.19.1 but none is installed. You must install peer dependencies yourself.
[task 2022-08-10T12:06:23.511Z] npm WARN node-fetch@2.6.7 requires a peer of encoding@^0.1.0 but none is installed. You must install peer dependencies yourself.
[task 2022-08-10T12:06:23.511Z] npm WARN postcss-load-config@3.1.0 requires a peer of ts-node@>=9.0.0 but none is installed. You must install peer dependencies yourself.
[task 2022-08-10T12:06:23.511Z] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: tar@4.4.19 (node_modules/fsevents/node_modules/tar):
[task 2022-08-10T12:06:23.511Z] npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/builds/worker/pdf.js/node_modules/.staging/tar-69971658' -> '/builds/worker/pdf.js/node_modules/fsevents/node_modules/tar'
[task 2022-08-10T12:06:23.511Z] 
[task 2022-08-10T12:06:23.511Z] added 9 packages from 5 contributors, removed 6 packages and updated 34 packages in 8.799s
[task 2022-08-10T12:06:23.511Z] /builds/worker/pdf.js/gulpfile.js:235
[task 2022-08-10T12:06:23.511Z]     output.library?.type === "module" ? { outputModule: true } : undefined;
[task 2022-08-10T12:06:23.511Z]                    ^
[task 2022-08-10T12:06:23.511Z] 
[task 2022-08-10T12:06:23.511Z] SyntaxError: Unexpected token .
[task 2022-08-10T12:06:23.511Z]     at Module._compile (internal/modules/cjs/loader.js:723:23)
[task 2022-08-10T12:06:23.511Z]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[task 2022-08-10T12:06:23.511Z]     at Module.load (internal/modules/cjs/loader.js:653:32)
[task 2022-08-10T12:06:23.511Z]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[task 2022-08-10T12:06:23.511Z]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[task 2022-08-10T12:06:23.511Z]     at Module.require (internal/modules/cjs/loader.js:692:17)
[task 2022-08-10T12:06:23.511Z]     at require (internal/modules/cjs/helpers.js:25:18)
[task 2022-08-10T12:06:23.511Z]     at requireOrImport (/usr/local/lib/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
[task 2022-08-10T12:06:23.511Z]     at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
[task 2022-08-10T12:06:23.511Z]     at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp-cli/index.js:211:24)
[task 2022-08-10T12:06:23.511Z] ~/checkouts/gecko/toolkit/components/pdfjs
[task 2022-08-10T12:06:23.511Z] cp: cannot stat '/builds/worker/pdf.js/build/mozcentral/browser/extensions/pdfjs/content/LICENSE': No such file or directory
[task 2022-08-10T12:06:23.511Z] cp: cannot stat '/builds/worker/pdf.js/build/mozcentral/browser/extensions/pdfjs/content/README.mozilla': No such file or directory
[task 2022-08-10T12:06:23.511Z] cp: cannot stat '/builds/worker/pdf.js/build/mozcentral/browser/extensions/pdfjs/content/PdfJsDefaultPreferences.jsm': No such file or directory
[task 2022-08-10T12:06:23.511Z] sending incremental file list
[task 2022-08-10T12:06:23.511Z] rsync: change_dir "/builds/worker/pdf.js/build/mozcentral/browser/extensions/pdfjs/content/build" failed: No such file or directory (2)
[task 2022-08-10T12:06:23.511Z] 
[task 2022-08-10T12:06:23.511Z] sent 20 bytes  received 12 bytes  64.00 bytes/sec
[task 2022-08-10T12:06:23.511Z] total size is 0  speedup is 0.00
[task 2022-08-10T12:06:23.511Z] rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
[task 2022-08-10T12:06:23.511Z] sending incremental file list
[task 2022-08-10T12:06:23.511Z] rsync: change_dir "/builds/worker/pdf.js/build/mozcentral/browser/extensions/pdfjs/content/web" failed: No such file or directory (2)
[task 2022-08-10T12:06:23.511Z] 
[task 2022-08-10T12:06:23.511Z] sent 20 bytes  received 12 bytes  64.00 bytes/sec
[task 2022-08-10T12:06:23.511Z] total size is 0  speedup is 0.00
[task 2022-08-10T12:06:23.511Z] rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
[task 2022-08-10T12:06:23.511Z] /builds/worker/pdf.js/build/mozcentral/browser/:
[task 2022-08-10T12:06:23.511Z] extensions
[task 2022-08-10T12:06:23.511Z] 
[task 2022-08-10T12:06:23.511Z] /builds/worker/pdf.js/build/mozcentral/browser/extensions:
[task 2022-08-10T12:06:23.511Z] pdfjs
[task 2022-08-10T12:06:23.511Z] 
[task 2022-08-10T12:06:23.511Z] /builds/worker/pdf.js/build/mozcentral/browser/extensions/pdfjs:
[task 2022-08-10T12:06:23.511Z] README.mozilla
[task 2022-08-10T12:06:23.511Z] cp: cannot stat '/builds/worker/pdf.js/build/mozcentral/browser/locales/en-US/pdfviewer/*.properties': No such file or directory
[task 2022-08-10T12:06:23.511Z] Registering changes with version control.
[task 2022-08-10T12:06:23.511Z] Checking for a spurious update.
[task 2022-08-10T12:06:23.511Z] Upstream e1e97c6edd8729e968bde47f60a1901e8e649901 hasn't modified files locally.
[task 2022-08-10T12:06:23.511Z] 
[task 2022-08-10T12:06:23.511Z] [Debug]   CommandProvider: -------
[task 2022-08-10T12:06:23.511Z] [Debug]   CommandProvider: stderr:
[task 2022-08-10T12:06:23.511Z] [Debug]   CommandProvider: 
[task 2022-08-10T12:06:23.511Z] [Debug]   CommandProvider: ----------------------------------------------
[task 2022-08-10T12:06:23.511Z] [Info]    VendorProvider: Ending VendorProvider.vendor
[task 2022-08-10T12:06:23.511Z] [Info]    VendorTaskRunner: Version e1e97c6edd8729e968bde47f60a1901e8e649901 was a spruious update.
```

The update script fails and because it doesn't edit any files, it's detected as a spurious update.  

So we need to figure out why the script is failing _and_ why we don't detect the failure and throw some sort of error to someone.

**Comment by tomrittervg** [comment]
The script failure at least seems to be caused by using an ancient version of node in the default apt repo.  https://github.com/nodesource/distributions/blob/master/README.md can help us get the latest LTS version.

**Comment by calixteman** [comment]
Any news on this issue ?
The bot is still broken for pdfjs updates.

**Comment by tomrittervg** [comment]
See https://github.com/mozilla/pdf.js/issues/15374 for why we don't detect the script failing.  I have a working run on holly and should be able to get a patch up soon

**Comment by tomrittervg** [comment]
Given the pdf.js issue is closed; and https://bugzilla.mozilla.org/show_bug.cgi?id=1788284 landed; this should be resolved.
